config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :guests do
    resources :parking_passes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "guests#index"
end

app/models/guest.rb
class Guest < ApplicationRecord
belongs_to :group
has_many :parking_passes, dependent: :destroy
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  before_action :set_guest, only: %i[ show edit update destroy ]

  # GET /guests or /guests.json
  def index
    @guests = Current.user.group.guests.all
  end

  # GET /guests/1 or /guests/1.json
  def show
  end

  # GET /guests/new
  def new
    @guest = Guest.new
  end

  # GET /guests/1/edit
  def edit
  end

  # POST /guests or /guests.json
  def create
    @guest = Current.user.group.guests.new(guest_params)

    respond_to do |format|
      if @guest.save
        format.html { redirect_to guests_path, notice: "Guest was successfully created." }
        format.json { render :show, status: :created, location: @guest }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /guests/1 or /guests/1.json
  def update
    respond_to do |format|
      if @guest.update(guest_params)
        format.html { redirect_to guests_path, notice: "Guest was successfully updated." }
        format.json { render :show, status: :ok, location: @guest }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @guest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /guests/1 or /guests/1.json
  def destroy
    @guest.destroy!

    respond_to do |format|
      format.html { redirect_to guests_path, status: :see_other, notice: "Guest was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_guest
      @guest = Guest.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def guest_params
      params.expect(guest: [ :name, :email ])
    end
end

app/helpers/guests_helper.rb
module GuestsHelper
end

app/views/guests/_form.html.erb
<%= form_with(model: guest, class: "contents") do |form| %>
  <% if guest.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(guest.errors.count, "error") %> prohibited this guest from being saved:</h2>

      <ul class="list-disc ml-6">
        <% guest.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": guest.errors[:name].none?, "border-red-400 focus:outline-red-600": guest.errors[:name].any?}] %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": guest.errors[:email].none?, "border-red-400 focus:outline-red-600": guest.errors[:email].any?}] %>
  </div>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/guests/_guest.html.erb
<div id="<%= dom_id guest %>" class="min-w-56 sm:w-auto my-5 space-y-5">
  <div>
    <%= guest.name %>
  </div>
</div>

app/views/guests/edit.html.erb
<% content_for :title, "Editing guest" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing guest</h1>

  <%= render "form", guest: @guest %>
  <div class=" inline-flex gap-2">
  <%= link_to "Back to guests", guests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Delete Guest", @guest, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
  </div>
</div>

app/views/guests/index.html.erb
<% content_for :title, "Guests" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Guests</h1>
    <%= link_to "New guest", new_guest_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="guests" class="min-w-full divide-y divide-gray-200 space-y-5 mt-5">
    <% if @guests.any? %>
      <% @guests.each do |guest| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0 space-y-5">
          <%= render guest %>
          <div>
            <% if guest.parking_passes.last&.active? %>
            <%= link_to "Active Pass", edit_guest_parking_pass_path(guest.id, guest.parking_passes.last), class: "bg-green-400 text-green-50 font-semibold rounded-full px-4 py-2 hover:bg-green-300"%>
            <% elsif guest.parking_passes.last %>
            <%= link_to "Pass Expired", edit_guest_parking_pass_path(guest.id, guest.parking_passes.last), class: "bg-red-400 text-red-50 font-semibold rounded-full px-4 py-2 hover:bg-red-300"%>
            <% end %>
          </div>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <% if !guest.parking_passes.last %>
            <%= link_to "Create Parking Pass", new_guest_parking_pass_path(guest.id, guest.parking_passes.last), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <% end %>
            <%= link_to "Edit Guest", edit_guest_path(guest), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No guests found.</p>
    <% end %>
  </div>
</div>

app/views/guests/new.html.erb
<% content_for :title, "New guest" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New guest</h1>

  <%= render "form", guest: @guest %>

  <%= link_to "Back to guests", guests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/guests/show.html.erb
<% content_for :title, "Showing guest" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Showing guest</h1>

  <%= render @guest %>

  <%= link_to "Edit this guest", edit_guest_path(@guest), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= link_to "Back to guests", guests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%= button_to "Destroy this guest", @guest, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>