config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :guests do
    resources :parking_passes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "guests#index"
end

app/models/parking_pass.rb
class ParkingPass < ApplicationRecord
  belongs_to :guest
  has_and_belongs_to_many :valid_days

  def active?
    if expiration_date
      expiration_date && expiration_date >= Date.today
    else
      true
    end
  end
end

app/controllers/parking_passes_controller.rb
class ParkingPassesController < ApplicationController
  allow_unauthenticated_access only: %i[ show ]
  before_action :set_parking_pass, only: %i[ show edit update destroy ]
  before_action :set_guest, only: %i[ new create edit update ]

  # GET /parking_passes or /parking_passes.json
  def index
    @parking_passes = ParkingPass.all
  end

  # GET /parking_passes/1 or /parking_passes/1.json
  def show
  end

  # GET /parking_passes/new
  def new
    @parking_pass = ParkingPass.new
  end

  # GET /parking_passes/1/edit
  def edit
  end

  # POST /parking_passes or /parking_passes.json
  def create
    @parking_pass = @guest.parking_passes.new(parking_pass_params)

      if @parking_pass.save
        qrcode = generate_parking_pass(@parking_pass)
        @parking_pass.update(qr_code: qrcode)
        ParkingPassMailer.with(parking_pass: @parking_pass, guest: @guest).send_pass.deliver_later
        redirect_to edit_guest_parking_pass_path(@guest.id, @parking_pass), notice: "Parking pass was successfully created."
      else
        render :new, status: :unprocessable_entity
      end
  end

  # PATCH/PUT /parking_passes/1 or /parking_passes/1.json
  def update
    respond_to do |format|
      if @parking_pass.update(parking_pass_params)
        ParkingPassMailer.with(parking_pass: @parking_pass, guest: @guest).send_pass.deliver_later
        format.html { redirect_to guests_path, notice: "Parking pass was successfully updated." }
        format.json { render :show, status: :ok, location: @parking_pass }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parking_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parking_passes/1 or /parking_passes/1.json
  def destroy
    @parking_pass.destroy!

    respond_to do |format|
      format.html { redirect_to guests_path, status: :see_other, notice: "Parking pass was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking_pass
      @parking_pass = ParkingPass.find(params.expect(:id))
    end

    def set_guest
      @guest = Guest.find(params.expect(:guest_id))
    end

    # Only allow a list of trusted parameters through.
    def parking_pass_params
      params.expect(parking_pass: [ :expiration_date, :qr_code, :valid_day, :guest_id, :valid_day_ids ])
    end

    def generate_parking_pass(parking_pass)
      RQRCode::QRCode.new(guest_parking_pass_url(parking_pass.guest_id, parking_pass.id)).as_svg(viewbox: true)
    end
end

app/helpers/parking_passes_helper.rb
module ParkingPassesHelper
end

app/views/parking_passes/_form.html.erb
<%= form_with(model: [guest, parking_pass], class: "contents") do |form| %>
  <% if parking_pass.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2><%= pluralize(parking_pass.errors.count, "error") %> prohibited this parking_pass from being saved:</h2>

      <ul class="list-disc ml-6">
        <% parking_pass.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :expiration_date, "Expiration Date (Leave blank if no expiration date)" %>
    <%= form.date_field :expiration_date, class: ["block shadow-sm rounded-md border px-3 py-2 mt-2 w-full", {"border-gray-400 focus:outline-blue-600": parking_pass.errors[:expiration_date].none?, "border-red-400 focus:outline-red-600": parking_pass.errors[:expiration_date].any?}] %>
  </div>

<% if @parking_pass.qr_code %>
  <p>(Scan with your phone to see if this pass is valid)</p>
   <div class="my-5 w-52 h-52">
    <%= raw(@parking_pass.qr_code) %>
  </div>
  <% end %>

  <%# <div class="my-5">
    <%# <%= form.label :valid_day_id, "Valid on selected days (Or leave blank for everyday use)" %>
    <%# <%= form.collection_check_boxes :valid_day_ids, ValidDay.order(:id), :id, :name %>
  <%# </div> %>

  <div class="inline">
    <%= form.submit class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/parking_passes/_parking_pass.html.erb
<div id="<%= dom_id parking_pass %>" class="w-full sm:w-auto my-5 space-y-5">
  <div>
    <strong class="block font-medium mb-1">Expiration date:</strong>
    <%= parking_pass.expiration_date %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Qr code:</strong>
    <%= parking_pass.qr_code %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Valid day:</strong>
    <%= parking_pass.valid_day %>
  </div>
  <div>
    <strong class="block font-medium mb-1">Guest:</strong>
    <%= parking_pass.guest_id %>
  </div>
</div>

app/views/parking_passes/edit.html.erb
<% content_for :title, "Editing parking pass" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing parking pass</h1>

  <%= render "form", parking_pass: @parking_pass, guest: @guest %>

  <%= link_to "Back to guests", guests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/parking_passes/index.html.erb
<% content_for :title, "Parking passes" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Parking passes</h1>
    <%= link_to "New parking pass", new_parking_pass_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium" %>
  </div>

  <div id="parking_passes" class="min-w-full divide-y divide-gray-200 space-y-5">
    <% if @parking_passes.any? %>
      <% @parking_passes.each do |parking_pass| %>
        <div class="flex flex-col sm:flex-row justify-between items-center pb-5 sm:pb-0">
          <%= render parking_pass %>
          <div class="w-full sm:w-auto flex flex-col sm:flex-row space-x-2 space-y-2">
            <%= link_to "Show", parking_pass, class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= link_to "Edit", edit_parking_pass_path(parking_pass), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
            <%= button_to "Destroy", parking_pass, method: :delete, class: "w-full sm:w-auto rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
          </div>
        </div>
      <% end %>
    <% else %>
      <p class="text-center my-10">No parking passes found.</p>
    <% end %>
  </div>
</div>

app/views/parking_passes/new.html.erb
<% content_for :title, "New parking pass" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New parking pass</h1>

  <%= render "form", parking_pass: @parking_pass, guest: @guest %>

  <%= link_to "Back to guests", guests_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
</div>

app/views/parking_passes/show.html.erb
<% content_for :title, "Showing parking pass" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl">Your parking pass is:</h1>

  <% if @parking_pass.active? %>
  <div class="font-bold text-8xl bg-green-400 text-green-50 h-96 w-96 flex justify-center items-center mt-5">
    <div>Active!</div>
  </div>
  <% else %>
  <div class="font-bold text-8xl bg-red-400 text-red-50 h-96 w-96 flex justify-center items-center mt-5">
    <div>Expired!</div>
  </div>
  <% end %>

  <%# <%= link_to "Edit this parking pass", edit_parking_pass_path(@parking_pass), class: "w-full sm:w-auto text-center rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%# <%= link_to "Back to parking passes", parking_passes_path, class: "w-full sm:w-auto text-center mt-2 sm:mt-0 sm:ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium" %>
  <%# <%= button_to "Destroy this parking pass", @parking_pass, method: :delete, form_class: "sm:inline-block mt-2 sm:mt-0 sm:ml-2", class: "w-full rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium cursor-pointer", data: { turbo_confirm: "Are you sure?" } %>
</div>